

language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
#  - zip -r springBootPrj *
#  - mkdir -p deploy
#  - mv springBootPrj.zip deploy/springBootPrj.zip

  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/springBootPrj.zip

deploy:
 - provider: s3
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
   bucket: springbootprj-build
   region: ap-northeast-2
   skip_cleanup: true
   acl: private
   local_dir: deploy
   wait-until-deployed: true

 - provider: codedeploy
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
   bucket: springbootprj-build
   key: springBootPrj.zip
   bundle_type: zip
   application: SpringBootPrj
   deployment_group: SpringBootPrj-group
   region: ap-northeast-2
   wait-until-deployed: true


# CI 완료시 메일로 알람
notifications:
  email:
    recipients:
      - huchuchu.yoo@gmail.com


